version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "candidatesdb"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "userpassword"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  document-db:
    image: mongo:6.0.4
    restart: always
    container_name: candidate_api_users
    environment:
      MONGO_INITDB_ROOT_USERNAME: master
      MONGO_INITDB_ROOT_PASSWORD: laboratory
      MONGO_INITDB_DATABASE: users
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

volumes:
  mysql_data: